### ISSUE TITLE
Apple official documents not being translated

### ISSUE THREAD

**Issue by KaitoMuraoka** [kishikawakatsumi/WebTranslator#223] opened 2024-03-07 15:47 UTC
I can't translate [Apple Developer documents](https://developer.apple.com/documentation/swift).
Neither pop-ups nor the shortcut key (⌘+⇧+y) respond.

I feel like this issue could occur elsewhere as well, 
but at least for now, it's not happening with anything other than Developer documents.

## Version
Web Translator : Version 0.1.32
Safari : Version 17.2.1

| Apple Developer Document | StackOverflow |
---|---
| <img src="https://github.com/kishikawakatsumi/WebTranslator/assets/70003919/1ddc3502-4ad6-4f67-adcb-aa1d62c37293" width=300> | <img src="https://github.com/kishikawakatsumi/WebTranslator/assets/70003919/5728fb71-55ff-48e4-8ba9-4b625eda6ec6" width=300>

<details>
<summary>日本語</summary>

[Appleの公式ドキュメント](https://developer.apple.com/documentation/swift)だけ翻訳ができません。
ポップアップも、ショートカットキー(⌘+⇧+Y)でも反応しません。

他の場所でも同様の問題は発生しそうな気はしますが、
少なくとも、今のところはAppleの公式ドキュメント以外は発生していません。

## バージョン
WebTranslator：Version 0.1.32
Safari Version 17.2.1 
</details>

**Comment by kishikawakatsumi** [comment] 2024-03-08 11:48
Thanks for reporting.

This is due to the Content Security Policy response header on Apple's website blocking the CSS in the extension. In fact, the translation functionality is working but is not being displayed as intended. If you scroll to the bottom of the screen after running the translation, you will find elements with no popover style applied.

This problem cannot be easily fixed as it requires replacing all CSS application with JavaScript.

Alternatively, if you use the full-text translation feature, it will work correctly since it does not use CSS.

**Comment by kishikawakatsumi** [comment] 2024-03-30 16:50
@KaitoMuraoka Fixed in version `0.1.33 (323)`. Please install and check it from the TestFlight link below.

https://testflight.apple.com/join/QmZCoDZb

**Comment by KaitoMuraoka** [comment] 2024-03-31 13:19
@kishikawakatsumi 

Thank you!
I'm really happy that you addressed this issue.

![スクリーンショット 2024-03-31 22 12 40](https://github.com/kishikawakatsumi/WebTranslator/assets/70003919/ed1f5bff-6ca4-4199-9456-189d5b6094f4)

It is currently working without any problems.
I'm growing even fonder of this web extension.
If anything comes up, I will provide feedback via TestFlight.

Feel free to close this Issue.

**Closed** 2024-03-31 15:58 UTC
